"""Event model and the contract every engine implements.

An *event* in NETRA is not a frame classification. It is a hypothesis about the
road that accumulated enough evidence, over enough time, to be worth an
operator's attention -- and that carries with it the numbers that produced it.

Two values are kept rigorously separate, because conflating them is the most
common way these systems mislead their users:

``confidence``  how sure the algorithm is that the event is real
``severity``    how disruptive or dangerous the event would be *if* real

A blocked carriageway we are only 60% sure about is still a high-severity
event. Folding uncertainty into severity would rank it below a certain but
trivial one, and an operator would be sent to the wrong place. They are
reported side by side and multiplied only to order the queue.
"""

from __future__ import annotations

import itertools
from dataclasses import dataclass, field
from typing import Any

_counter = itertools.count(1)


# event type constants
WRONG_WAY = "wrong_way"
LANE_VIOLATION = "lane_violation"
QUEUE = "queue"
BLOCKAGE = "blockage"
COLLISION = "collision_candidate"
STOPPED = "abnormal_stop"
PEDESTRIAN = "pedestrian_on_carriageway"

EVENT_LABELS = {
    WRONG_WAY: "Wrong-side movement",
    LANE_VIOLATION: "Wrong lane crossing",
    QUEUE: "Queue / congestion",
    BLOCKAGE: "Road blockage",
    COLLISION: "Suspected collision-related disruption",
    STOPPED: "Abnormal stop",
    PEDESTRIAN: "Pedestrian on carriageway",
}

# Which events a machine may confirm on its own, and which always need a human.
# Anything that could dispatch an ambulance is not the algorithm's decision.
AUTO_CONFIRMABLE = {WRONG_WAY, QUEUE, LANE_VIOLATION}
ALWAYS_VERIFY = {COLLISION, BLOCKAGE}


@dataclass
class Event:
    """A single incident hypothesis with its full evidential trail."""

    type: str
    camera_id: str
    started_t: float                  # seconds into the clip -- the ONSET
    detected_t: float                 # when the system actually raised it
    confidence: float
    corridor_id: str | None = None
    track_ids: list[int] = field(default_factory=list)
    triggers: dict[str, Any] = field(default_factory=dict)
    severity: float = 0.0
    severity_label: str = "Low"
    severity_parts: dict[str, float] = field(default_factory=dict)
    ended_t: float | None = None
    onset_method: str = "detection"
    onset_recovered_s: float = 0.0
    evidence: dict[str, Any] = field(default_factory=dict)
    location: dict[str, Any] = field(default_factory=dict)
    recommended_action: str = ""
    operational_context: dict[str, Any] = field(default_factory=dict)
    status: str = "detected"
    id: int = field(default_factory=lambda: next(_counter))

    @property
    def label(self) -> str:
        return EVENT_LABELS.get(self.type, self.type)

    @property
    def duration(self) -> float:
        end = self.ended_t if self.ended_t is not None else self.detected_t
        return max(0.0, end - self.started_t)

    @property
    def needs_verification(self) -> bool:
        # A direction learned from observed traffic is useful calibration
        # evidence, but it is not a legal fact.  Wrong-side findings remain
        # candidates until an operator has reviewed the configured direction.
        direction_unreviewed = (
            self.type == WRONG_WAY
            and self.triggers.get("legal_direction_reviewed") is False
        )
        return (self.type in ALWAYS_VERIFY or self.confidence < 0.60
                or direction_unreviewed)

    @property
    def priority(self) -> float:
        """Ordering key for the operator queue: expected operational significance."""
        return self.severity * self.confidence

    @property
    def detection_delay(self) -> float:
        """How long after onset the alarm was raised. Reported, never hidden."""
        return max(0.0, self.detected_t - self.started_t)

    def explain(self) -> str:
        """One-line human-readable reason, built from the triggers themselves.

        Deliberately templated from structured values rather than generated by
        a language model. The operator needs the number that fired, not prose
        about it -- and a template cannot hallucinate.
        """
        t = self.triggers
        if self.type == WRONG_WAY:
            return (f"Track {self.track_ids[0] if self.track_ids else '?'} moved against "
                    f"corridor {self.corridor_id} for {t.get('persistence_s', 0):.1f}s "
                    f"(alignment {t.get('alignment', 0):+.2f}, "
                    f"displacement {t.get('displacement_px', 0):.0f}px)")
        if self.type == QUEUE:
            return (f"{t.get('vehicles', 0)} vehicles in {self.corridor_id}, median speed "
                    f"{t.get('median_speed_px', 0):.1f}px/s "
                    f"({t.get('speed_drop_pct', 0):.0f}% below baseline), "
                    f"occupancy {t.get('occupancy', 0):.0%}, "
                    f"sustained {t.get('persistence_s', 0):.0f}s")
        if self.type == BLOCKAGE:
            return (f"Track {self.track_ids[0] if self.track_ids else '?'} stationary "
                    f"{t.get('stationary_s', 0):.0f}s in {self.corridor_id}; "
                    f"upstream flow down {t.get('flow_drop_pct', 0):.0f}%, "
                    f"persistent in long background: {t.get('in_long_background', False)}")
        if self.type == COLLISION:
            parts = []
            if t.get("proximity_px") is not None:
                parts.append(f"separation {t['proximity_px']:.0f}px")
            if t.get("approach_angle_deg") is not None:
                parts.append(f"approach angle {t['approach_angle_deg']:.0f}deg")
            if t.get("decel_px_s2") is not None:
                parts.append(f"deceleration {t['decel_px_s2']:.0f}px/s^2")
            if t.get("changepoint_z") is not None:
                parts.append(f"motion change-point z={t['changepoint_z']:.2f}")
            return "Conflict indicators: " + ", ".join(parts) if parts else "Motion change-point"
        if self.type == LANE_VIOLATION:
            return (f"Track {self.track_ids[0] if self.track_ids else '?'} crossed a solid "
                    f"boundary {t.get('from_corridor')} -> {t.get('to_corridor')}")
        if self.type == PEDESTRIAN:
            return (f"Person track {self.track_ids[0] if self.track_ids else '?'} inside "
                    f"carriageway {self.corridor_id} for {t.get('dwell_s', 0):.1f}s")
        if self.type == STOPPED:
            return (f"Track {self.track_ids[0] if self.track_ids else '?'} stationary "
                    f"{t.get('stationary_s', 0):.0f}s in a no-stop zone")
        return self.label

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "type": self.type,
            "label": self.label,
            "camera_id": self.camera_id,
            "corridor_id": self.corridor_id,
            "started_t": round(self.started_t, 3),
            "detected_t": round(self.detected_t, 3),
            "ended_t": round(self.ended_t, 3) if self.ended_t is not None else None,
            "duration": round(self.duration, 3),
            "detection_delay": round(self.detection_delay, 3),
            "onset_method": self.onset_method,
            "onset_recovered_s": round(self.onset_recovered_s, 3),
            "confidence": round(self.confidence, 4),
            "severity": round(self.severity, 4),
            "severity_label": self.severity_label,
            "severity_parts": {k: round(float(v), 4) for k, v in self.severity_parts.items()},
            "priority": round(self.priority, 4),
            "track_ids": list(self.track_ids),
            "triggers": self.triggers,
            "explanation": self.explain(),
            "needs_verification": self.needs_verification,
            "status": self.status,
            "evidence": self.evidence,
            "location": self.location,
            "recommended_action": self.recommended_action,
            "operational_context": self.operational_context,
        }


class EventEngine:
    """Base class. Engines are stateful across frames by design.

    An engine sees every processed frame and decides nothing on any single one;
    it accumulates evidence and lets a CUSUM decide when that evidence is
    sufficient. ``update`` returns newly-raised events only.

    Deduplication is built in here rather than left to each engine, because
    getting it wrong is the single fastest way to make the system useless. An
    incident that lasts ten minutes must produce *one* incident that stays open
    and updates, not six hundred alerts. Every engine therefore claims a
    ``dedupe_key`` (a track, a corridor, a pair) and the base class enforces:

    * one open incident per key at a time
    * a refractory period after an incident closes, so a flickering condition
      cannot machine-gun the operator
    * an update path, so a live incident's numbers stay current
    """

    name = "base"
    cooldown_s = 30.0

    def __init__(self, scene, config: dict):
        self.scene = scene
        self.config = config
        self.active: dict[str, Event] = {}
        self._last_fired: dict[str, float] = {}

    # -- deduplication -----------------------------------------------------
    def can_fire(self, key: str, t: float) -> bool:
        """False while an incident for this key is open or still cooling down."""
        if key in self.active:
            return False
        last = self._last_fired.get(key)
        return last is None or (t - last) >= self.cooldown_s

    def register(self, key: str, event: Event, t: float) -> Event:
        self.active[key] = event
        self._last_fired[key] = t
        return event

    def close(self, key: str, t: float) -> None:
        ev = self.active.pop(key, None)
        if ev is not None and ev.ended_t is None:
            ev.ended_t = t
        self._last_fired[key] = t

    def touch(self, key: str, t: float) -> Event | None:
        """Keep an open incident alive; returns it so the engine can refresh it."""
        ev = self.active.get(key)
        if ev is not None:
            ev.ended_t = None
            self._last_fired[key] = t
        return ev

    def forget(self, key: str) -> None:
        self.active.pop(key, None)
        self._last_fired.pop(key, None)

    def update(self, ctx) -> list[Event]:      # pragma: no cover - interface
        raise NotImplementedError

    def close_all(self, t: float) -> None:
        for ev in self.active.values():
            if ev.ended_t is None:
                ev.ended_t = t
        self.active.clear()
